(function(){var f=null,i=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};function j(a,b,c){c!=f&&""!==c&&(a+=encodeURIComponent(b)+"="+encodeURIComponent(c)+"&");return a}function _google_json_callback(a){k();var b="google_afd_ad_request_done";if(window[b])window[b](a)}function l(a,b){var c=document;window._google_json_callback=_google_json_callback;if(b){var d=c.createElement("script");d.src=a;d.async=!0;c=c.getElementsByTagName("script")[0];c.parentNode.insertBefore(d,c)}else c.write('<script src="'+a+'"><\/script>')}
function m(){var a=window,b=document,c=2;try{c=a.top.document==b?0:a.top.document?1:2}catch(d){}return c}function n(a){if("array"==i(a)){for(var b=[],c=0;c<a.length;++c)b.push('"'+a[c].replace(RegExp('"',"ig"),'""')+'"');return b.join()}return"string"==typeof a?a:f}function o(a){var b=window,c=document,c=c.referrer;1==a&&(c=b.top.document.referrer);return c}
function p(a){var b=(new Date).getTime(),c=-(new Date).getTimezoneOffset(),d=m(),g=o(d);window.screen&&(a.u_h=window.screen.height,a.u_w=window.screen.width);var h;h=a.domain_name&&a.adtest&&"on"==a.adtest?a.domain_name:document.domain;var a={api:"2",adlh:a.adlh,callback:"_google_json_callback",output:"js",adtest:a.adtest,backfill:a.backfill,client:a.client,channel:a.channel,hl:a.hl,kw:a.kw,ip:a.ip,q:a.q,afdt:a.token,num_ads:a.num_ads,num_radlinks:a.num_radlinks,optimize_terms:a.optimize_terms,st:a.session_token,
categories:a.categories,terms:n(a.terms),feed:a.feed,ws_results:a.ws_results,adext:a.adext,vid:a.vid,max_radlink_len:a.max_radlink_length,adrep:a.adrep,domain_name:h,dt:b,u_tz:c,u_his:window.history.length,u_h:a.u_h,u_w:a.u_w,frm:d,ref:g},b="http://googleads.g.doubleclick.net/apps/domainpark/domainpark.cgi?",e;for(e in a)b=j(b,e,a[e]);return b=b.slice(0,-1).substring(0,2E3)}
function q(a){var b="ca-rs-"==a.client.substring(0,6)||"partner-rs-"==a.client.substring(0,11)||"rs-"==a.client.substring(0,3);if(!b&&!a.domain_name)return _google_json_callback({error_code:202}),f;var c=(new Date).getTime(),d=-(new Date).getTimezoneOffset(),g=m(),h=o(g);window.screen&&(a.u_h=window.screen.height,a.u_w=window.screen.width);(b="ca-"==a.client.substring(0,3))?a.q||(a.s=a.domain_name):(a.num=0,!a.ad&&a.max_num_ads&&(a.ad="n"+a.max_num_ads),!0!==a.user_search&&(a.qry_lnk=a.q));var a=
{callback:"_google_json_callback",output:"js",adlh:a.adlh,client:a.client,domain_name:a.domain_name,q:a.q,hl:a.hl,channel:a.channel,adtest:a.adtest,afdt:a.token,url:a.url,optimize_terms:a.optimize_terms,ip:a.ip,terms:n(a.terms),st:a.session_token,s:b?a.s:"",kw:b?a.kw:"",kw_type:b?a.kw_type:"",num_ads:b?a.num_ads:"",adsafe:b?a.adsafe:"",num_radlinks:b?a.num_radlinks:"",max_radlink_len:b?a.max_radlink_length:"",qry_lnk:b?"":a.qry_lnk,num:b?"":a.num,ad:b?"":a.ad,adext:b?"":a.adext,adpage:b?"":a.adpage,
gl:b?"":a.gl,gcs:b?"":a.gcs,gm:b?"":a.gm,gr:b?"":a.gr,ie:b?"":a.ie,oe:b?"":a.oe,adrep:b?"":a.adrep,dt:c,u_tz:d,u_his:window.history.length,u_h:a.u_h,u_w:a.u_w,frm:g,ref:h},b=b?"http://googleads.g.doubleclick.net/apps/domainpark/domainpark.cgi?":"http://domains.googlesyndication.com/domainads/search?",e;for(e in a)b=j(b,e,a[e]);return b=b.slice(0,-1).substring(0,2E3)}
function r(a){if(!a)return _google_json_callback({error_code:200}),f;return!a.client?(_google_json_callback({error_code:201}),f):a.api&&"2"==a.api?p(a):q(a)}function k(){var a=window;a.google_afd_request=f}function s(){var a=window.google_afd_request;window.onerror=t;var b=r(a);b&&l(b,a.async)}function t(){s();return!0}s();})()
